### PR TITLE
Add support for European users

### PR DESCRIPTION
**Pull request by matt1**
Adds a environment variable for the region to use - if not specified it uses the "world" config (what you currently have).  URLs, IDs, keys etc extracted from the APK as of 24th April 2020.

### CODE REVIEW

**Comment by matt1** [comment]
I needed it here otherwise there was a stacktrace about no module named 'Crypto'.  Removed it anyway.

**Comment by mbevand** [comment]
That's strange. What's your OS?

Anyway, I'm merging this, thanks again!

**Comment by matt1** [comment]
> That's strange. What's your OS?

Windows 10 and a clean install of Python 3.8.2

**Comment by mbevand** [comment]
Ah, ok. Well I added it back

**Pull request merged**
